### PR TITLE
Add missing RegExp.prototype[@@replace]

### PR DESCRIPTION
**Pull request by rbuckton**
Adds spec text to describe the behavior of `RegEexp.prototype[@@replace]` with match options.

### CODE REVIEW

**Review by ljharb — APPROVED** [review]

**Comment by rbuckton** [comment]
You can view a rendered version of the documentation changes here: https://tc39.es/proposal-regexp-match-offsets/pr/18/#sec-regexp.prototype-@@replace

**Comment by rbuckton** [comment]
This currently has the downside of calling `CoerceMatchResult` twice on `Get(result, "0")` (12.c.iii.2 and 15.d),  though we were previously calling `ToString` twice as well.

**Comment by rbuckton** [comment]
I am going to merge this. If reviewers have any further input please feel free to file in the individual or meta review issues.

**Comment by msaboff** [comment]
I'm fine with these changes.

**Pull request merged**
